{% set name = "cloudvision" %}
{% set version = "1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloudvision-{{ version }}.tar.gz
  sha256: f865cc7a5e324fbd6259454f5e2b056c381566349e797e0ddce2131b52d971e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0
    - setuptools >=62.1.0
    - pip
  run:
    - python >=3.7.0
    - cryptography <43.0.0,>=42.0.4
    - grpcio >=1.46.0
    - msgpack-python >=1.0.3
    - protobuf <4.0,>=3.20.1
    - requests >=2.20.1
    - typing-extensions >=4.2.0
    - types-protobuf <4.0,>=3.20.1
    - types-pyyaml >=6.0.7
    - types-requests >=2.27.25

test:
  imports:
    - cloudvision
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python library for Arista's CloudVision APIs and Provisioning Action integrations.
  dev_url: https://github.com/aristanetworks/cloudvision-python
  license: Apache-2.0
  license_file: COPYING

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/47182
    reason: Client request
  recipe-maintainers:
    - anaobi
